name: flutter_alarm_clock
description: A lightweight flutter package connecting android clock app intents.
version: 0.1.2
homepage: https://sebastjanmevlja.me/
repository: https://github.com/mevljas/flutter_alarm_clock

environment:
  sdk: '>=2.14.0 <4.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter:
  plugin:
    platforms:
      android:
        package: tk.sebastjanmevlja.flutter_alarm_clock
        pluginClass: FlutterAlarmClockPlugin
